# Color Detection on Static Image

### Below are the Contents of Project:

>1. <a href="#Description">Description</a>
2. <a href="#Importing-the-Libraries">Importing the Libraries</a>
3. <a href="#Importing-the-Dataset">Importing the Dataset</a>
4. <a href="#Color-Detection">Color Detection</a>

### Description

><ol>
    <li>It is a process of identifying the color present in an image, or object or in video.</li><br>
    <li>It is related to analyzing the RGB (Red, Green, Blue) values of pixels in an image or video to
        determine the dominant color.</li><br>
    <li>It is the python code where static images is provided by the user and the image go through Color Detection    
        Algorithm, and in the next step the user gets to know the color of the part of image as whole and its RGB (Red 
        Green Blue) component.</li>
</ol>

### Importing the Libraries

><ol>
    <li> Importing the Basic Libraries of Python along with the cv2 libraries, which is used in computer application and    
        getting the color of the pixel.</li> <br>
    <li>For computers it is in 2D Array</li> <br>
</ol>

<div class="alert alert-block alert-warning">
<b>Imp:</b> In computer each pixel is made up of R-G-B components normally, but in opencv it is made up of B-G-R format
</div>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import colors

import cv2
from collections import Counter
from sklearn.cluster import KMeans

### Importing the Dataset

In [2]:
img_path = r"C:\Users\kshit\color detection project\Final\Dseu.jpeg"

# Since the dataset does not contain the the columns names in which data is present, we will create the column name
index = ['color', 'color_name', 'hex', 'R', 'G', 'B']

# Path of the file in the current sysytem
df = pd.read_csv(r"C:\Users\kshit\color detection project\Color detections\colors.csv", names=index, header=None)
df.head(10)

color             color_name      hex    R    G    B
0    air_force_blue_raf   Air Force Blue (Raf)  #5d8aa8   93  138  168
1   air_force_blue_usaf  Air Force Blue (Usaf)  #00308f    0   48  143
2  air_superiority_blue   Air Superiority Blue  #72a0c1  114  160  193
3       alabama_crimson        Alabama Crimson  #a32638  163   38   56
4            alice_blue             Alice Blue  #f0f8ff  240  248  255
5      alizarin_crimson       Alizarin Crimson  #e32636  227   38   54
6          alloy_orange           Alloy Orange  #c46210  196   98   16
7                almond                 Almond  #efdecd  239  222  205
8              amaranth               Amaranth  #e52b50  229   43   80
9                 amber                  Amber  #ffbf00  255  191    0

In [3]:
# Extracting the Particular Row

print('Total Number of Rows:',len(df))
print('\n')
print(df.loc[1])

Total Number of Rows: 865


color           air_force_blue_usaf
color_name    Air Force Blue (Usaf)
hex                         #00308f
R                                 0
G                                48
B                               143
Name: 1, dtype: object


### Color Detection

In [4]:
# Array of pixel
# cv2.imread is used when we have to read a image in the jupyter notebook itself, it read image in array format.

img=cv2.imread(img_path)
print(img)                # it will print an array of number, this is the way in which computer see the array of pixel.

# Resizing the image
img=cv2.resize(img,(800,600))

[[[104 162 204]
  [104 162 204]
  [104 162 204]
  ...
  [233 203 114]
  [233 203 114]
  [233 203 114]]

 [[104 162 204]
  [104 162 204]
  [104 162 204]
  ...
  [233 203 114]
  [233 203 114]
  [233 203 114]]

 [[104 162 204]
  [104 162 204]
  [104 162 204]
  ...
  [233 203 114]
  [233 203 114]
  [233 203 114]]

 ...

 [[  9  17  10]
  [  9  17  10]
  [  9  17  10]
  ...
  [131 196 241]
  [130 195 240]
  [129 194 239]]

 [[  8  16   9]
  [  9  17  10]
  [  9  17  10]
  ...
  [133 198 243]
  [132 197 242]
  [132 197 242]]

 [[  8  16   9]
  [  9  17  10]
  [  9  17  10]
  ...
  [134 199 244]
  [134 199 244]
  [133 198 243]]]


In [5]:
# when clicked no where

clicked=False
r=g=b=xpos=ypos=0

In [6]:
# Gives the Color Name from RGB

def get_color_name(R,G,B):
    minimum = 1000
    for i in range(len(df)):
        d = abs(R - int(df.loc[i,'R'])) + abs(G - int(df.loc[i,'G'])) + abs(B - int(df.loc[i,'B']))
        if d <= minimum:
            minimum = d
            cname = df.loc[i, 'color_name']
            
    return cname

In [7]:
# This function is used when we have to find color using mouse button.
# event is 'double clicking with mouse'

def draw_function(event, x, y, flags, params):
    if event == cv2.EVENT_LBUTTONDBLCLK:
        global b, g, r, xpos, ypos, clicked
        clicked = True
        xpos = x
        ypos = y
        b,g,r = img[y,x]
        b = int(b)
        g = int(g)
        r = int(r)


In [8]:
# Creating the window for image

cv2.namedWindow('image')
cv2.setMouseCallback('image',draw_function)

In [9]:
# To keep this programm running

while True:
    cv2.imshow('image', img)
    if clicked:
        
        # Creating the rectangle strip for the image
        #cv2.rectangle (image, startpoint, endpoint, color, thickness)-1 fills entire rectangle 
        cv2.rectangle(img, (20,20), (600,60), (b,g,r), -1)

        #Creating text string to display ( Color name and RGB values )
        text = get_color_name(r,g,b) + ' R=' + str(r) + ' G=' + str(g) + ' B=' + str(b)
        
        #cv2.putText(img,text,start,font(0-7),fontScale,color,thickness,lineType )
        cv2.putText(img, text, (50,50), 2,0.8, (255,255,255),2,cv2.LINE_AA)

        #For very light colours we will display text in black colour
        if r+g+b >=600:
            cv2.putText(img, text, (50,50), 2,0.8, (0,0,0),2,cv2.LINE_AA)
            
    # cv.waitKey is used to close the window, if 20 sec no movement
    if cv2.waitKey(20) & 0xFF == ord('q'):
        cv2.destroyAllWindows()
        break